version: '2'

services:
  traefik:
    container_name: traefik
    build: .
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      - CLOUDFLARE_EMAIL=${CF_EMAIL}
      - CLOUDFLARE_API_KEY=${CF_API_KEY}
      - TZ=${TIMEZONE}
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_PATH}/reverse_proxy/acme.json:/etc/traefik/acme.json
    networks:
      - default
    cap_drop:
      - all
    cap_add:
      - net_bind_service
